---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: topolvm-system
  name: topolvm-lvmd
data:
  lvmd.yaml: |
    socket-name: /run/topolvm/lvmd.sock
    device-classes:
      - name: ssd
        volume-group: myvg1
        default: true
        spare-gb: 10
