---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topolvm-system
  name: topolvm-lvmd
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: topolvm-system
  name: psp:topolvm-lvmd
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["topolvm-lvmd"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: topolvm-system
  name: topolvm-lvmd:psp:topolvm-lvmd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:topolvm-lvmd
subjects:
- kind: ServiceAccount
  namespace: topolvm-system
  name: topolvm-lvmd
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topolvm-system
  name: topolvm-lvmd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-lvmd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-lvmd
    spec:
      serviceAccountName: topolvm-lvmd
      hostPID: true
      containers:
        - name: lvmd
          image: quay.io/topolvm/topolvm-with-sidecar:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
          command:
            - /lvmd
            - --container
          volumeMounts:
            - name: lvmd-socket-dir
              mountPath: /run/topolvm
            - name: config
              mountPath: /etc/topolvm
      volumes:
        - name: config
          configMap:
            name: topolvm-lvmd
        - name: lvmd-socket-dir
          hostPath:
            path: /run/topolvm
            type: DirectoryOrCreate
